from func import show_name,show_preference,show_history,remember_me,show_note
from perm_func import the_creation_of_calyx,greeting,hello, name,bye,help_menu,calc,get_date,get_time,open_fb,open_google,open_insta,open_yt
from perm_func import open_calculator,open_chrome,open_file,open_vs_code,open_command,open_notepad
from storage import reset_memory
command={
    "hi": hello,
    "hey":hello,
    "sup":hello,
    "hello":hello,
    "good morning":greeting,
    "good afternoon":greeting,
    "good evening":greeting,
    "who are you":name,
    "what is your name":name,
    "bye":bye,
    "exit":bye,
    "good night":bye,
    "thanks":lambda:"My pleasure",
    "help" : help_menu,
    "calc" : calc,
    "time" : get_time,
    "date" : get_date,
    "what is my name" : show_name,
    "who am i": show_name,
    "what is my hobby" :lambda: show_preference("hobby"),
    "what is my favorite colour" :lambda: show_preference("colour"),
    "show history" : show_history,
    "history" : show_history,
    "what you know about me" : remember_me,
    "remember me" : remember_me, 
    "reset" : reset_memory,
    "when was calyx created" : the_creation_of_calyx ,
    "born" : the_creation_of_calyx,
    "start" : the_creation_of_calyx,
    "yt" : open_yt,
    "fb" : open_fb,
    "google" : open_google,
    "insta" : open_insta,
    "chrome" : open_chrome,
    "calc app": open_calculator,
    "file" : open_file,
    "vs code" : open_vs_code,
    "cmd" : open_command,
    "notepad" : open_notepad,
    "note" : show_note,
}

